#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#nx run-many --all --target=lint
nx run-many --projects=shared-helpers,shared-images,shared-ui-components,shared-ui-helpers,shared-ui-themes,usdb --target=lint
